components/dashboard.tsx, components/tickets-view.tsx
=> feat: add tickets page

components/api-key-card.tsx
Add token deletion confirmation.
Vizualize loading of tokens on refresh.
Closes #18
=> feat: add token delete confirmation

app/account-portal/page.tsx, components/LoadingCircle.tsx, components/credit-balance-card.tsx, contexts/app-state.tsx
Update the balance immediatelly after top-up.
Also add loading circle at the start of the balance page.
=> feat: update balance immediately

components/api-key-card.tsx
Fill the created by with the current user's name.
Closes #20
=> feat: fill created by with current user's name

app/settings/page.tsx
Make the email readonly.
Closes #22
=> feat: email readonly

app/playground/page.tsx, utils/utils.ts
Closes #30 
Also closes part1 of #33
=> feat: fetch playground models from proxy

components/AuthForm.tsx, components/credit-balance-card.tsx, components/top-nav.tsx
=> chore: login rename

app/globals.css
Change the color of the background hover square effect to match the orange theme.
=> chore: orange hover

components/sidebar.tsx
Make the chevron bigger.
Closes #31
=> chore: make the chevron bigger

app/playground/page.tsx
Update the playground models text overflow. 
Make parameters functional.
=> feat: update playground models text

app/globals.css, app/playground/page.tsx, components/parameters-sidebar.tsx, contexts/settings-context.tsx, utils/utils.ts
Updated the playground parameters UI to work with the full chat request body and also save user choice. 
Part of #17
=> feat: make playground parameters functional

.github/workflows/deploy.yaml, app/analytics/page.tsx, app/models/page.tsx, app/page.tsx, components/sidebar.tsx, lib/api.ts
On the network status pane add graphs from grafana.
Remove all the placeholders graphs from the app.
**This PR also changes the automatic release to the new version**
Closes #63 #62 #61 #57 #56 #29 #28 #16
=> feat: add grafana graphs

.github/workflows/deploy.yaml
When this is merged, the new dashboard should be automatically released.
=> chore: disable test

.github/workflows/deploy.yaml
Proper github action file (copied from `with-logic` branch)
=> fix: proper github action

next.config.mjs
=> fix: enable static page

.github/workflows/deploy.yaml
fix url env vars
enable zk-login
=> fix: build env vars

app/layout.tsx
=> chore: update title and description

components/api-key-card.tsx
=> chore: remove api learn more link

app/page.tsx, components/billing-summary-card.tsx
Cosmetic issues with formatting of dates, model names, text color
Closes #79
=> feat: formatting on tooltips

app/settings/page.tsx, components/top-nav.tsx, contexts/settings-context.tsx, lib/api.ts, lib/atoma.ts
Remove the name from the app and change the color of the profile icon to orange.
Closes #81
=> feat: remove the user's name

app/playground/page.tsx
=> fix: pixel issue on playground

app/guide/page.tsx, components/sidebar.tsx
Add guide
I change the original design to have dark/light mode. It was only dark.
Closes #106
=> feat: add guide
